/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package game;

import game.drawing.*;
import game.Screen;




public class App{
    
    public static void main(String[] args) {
        createAndShowGUI();
        
    }
      
    

    private static void createAndShowGUI() {
        Screen screen = new Screen();
        screen.addTo(new GamePanel());
        screen.buildScreen(500, 500);
        
        
    }

}