/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ICS201;
import javax.swing.*; 
import java.awt.*;

public class App {

    private static void createAndShowGUI() {
        //Create and set up the window.
        JFrame frame = new JFrame("HelloWorldSwing");
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

        //Add the ubiquitous "Hello World" label.
        JLabel label = new JLabel("Hello World");
        JLabel label2 = new JLabel("This is cringe af");
        Menu menu1 = new Menu("JOE MAMA");
        frame.getContentPane().add(label2);
        // frame.getMenuBar().add(menu1);
        

        //Display the window.
        frame.pack();
        frame.setVisible(true);
    }


    public static void main(String[] args) {
        javax.swing.SwingUtilities.invokeLater(new Runnable() {
            public void run() {
                createAndShowGUI();
            }
        });
    }
}
