/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ICS201;
// import javax.swing.*; 

import java.util.ArrayList;
import java.util.Scanner;

import javax.swing.JFrame;
import javax.swing.JLabel;
import java.awt.*;



public class App{



    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);
        System.out.println("Number One");
        String number1 = scanner.nextLine();
        int num1 = Integer.parseInt(number1.trim());

        // createAndShowGUI();
    }

    public static int isInt(){
        try{



        }except
    }







    // private static void createAndShowGUI() {
    //     // Create and set up the window.
    //     JFrame frame = new JFrame("HelloWorldSwing");
    //     frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        

    //     // Add the ubiquitous "Hello World" label.
    //     JLabel label = new JLabel("Hello World");
    //     frame.add(label);

    //     // Display the window.
    //     frame.pack();
    //     frame.setSize(500, 500);
    //     frame.setVisible(true);

    // }


}

